download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/mafalb-squid-0.2.0.tar.gz
format_version: 1.0.0
name: squid
namespace: mafalb
server: https://galaxy.ansible.com/api/
signatures: []
version: 0.2.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/mafalb/squid/versions/0.2.0/
