# vim: set ft=yaml ts=2 expandtab:
---

- name: Include OS specific variables
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version in ['6', '7']
...
